-- Blind 75 Migration - Part 4: Final Categories
-- Complete all remaining problems to reach 75 total

INSERT INTO problems (id, title, difficulty, category_id, description, function_signature, examples, constraints, hints, likes, dislikes, acceptance_rate) VALUES

-- 1-D Dynamic Programming (12 problems)
('climbing-stairs', 'Climbing Stairs', 'Easy',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps.',
 'def climbStairs(self, n: int) -> int:',
 '[{"input": "n = 2", "output": "2"}, {"input": "n = 3", "output": "3"}]'::jsonb,
 '["1 <= n <= 45"]'::jsonb,
 '["This is fibonacci sequence", "Use dynamic programming"]'::jsonb,
 8901, 234, 52.1),

('house-robber', 'House Robber', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'You are a professional robber. You cannot rob two adjacent houses.',
 'def rob(self, nums: List[int]) -> int:',
 '[{"input": "nums = [1,2,3,1]", "output": "4"}, {"input": "nums = [2,7,9,3,1]", "output": "12"}]'::jsonb,
 '["1 <= nums.length <= 100", "0 <= nums[i] <= 400"]'::jsonb,
 '["For each house: rob it or not", "Track max money up to current house"]'::jsonb,
 7890, 167, 49.8),

('house-robber-ii', 'House Robber II', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'All houses at this place are arranged in a circle. Adjacent houses have security systems connected.',
 'def rob(self, nums: List[int]) -> int:',
 '[{"input": "nums = [2,3,2]", "output": "3"}, {"input": "nums = [1,2,3,1]", "output": "4"}]'::jsonb,
 '["1 <= nums.length <= 100", "0 <= nums[i] <= 1000"]'::jsonb,
 '["Cannot rob first and last together", "Two cases: rob first or rob last"]'::jsonb,
 4567, 189, 39.3),

('longest-palindromic-substring', 'Longest Palindromic Substring', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'Given a string s, return the longest palindromic substring in s.',
 'def longestPalindrome(self, s: str) -> str:',
 '[{"input": "s = \"babad\"", "output": "\"bab\""}, {"input": "s = \"cbbd\"", "output": "\"bb\""}]'::jsonb,
 '["1 <= s.length <= 1000", "s consist of only digits and English letters"]'::jsonb,
 '["Expand around centers", "Check odd and even length palindromes"]'::jsonb,
 9876, 345, 32.8),

('palindromic-substrings', 'Palindromic Substrings', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'Given a string s, return the number of palindromic substrings in it.',
 'def countSubstrings(self, s: str) -> int:',
 '[{"input": "s = \"abc\"", "output": "3"}, {"input": "s = \"aaa\"", "output": "6"}]'::jsonb,
 '["1 <= s.length <= 1000", "s consists of lowercase English letters"]'::jsonb,
 '["Expand around centers", "Count palindromes of all lengths"]'::jsonb,
 5678, 123, 66.1),

('decode-ways', 'Decode Ways', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'A message containing letters from A-Z can be encoded into numbers using the mapping A=1, B=2, ..., Z=26.',
 'def numDecodings(self, s: str) -> int:',
 '[{"input": "s = \"12\"", "output": "2"}, {"input": "s = \"226\"", "output": "3"}]'::jsonb,
 '["1 <= s.length <= 100", "s contains only digits"]'::jsonb,
 '["Check single digit and two digit decodings", "Handle leading zeros"]'::jsonb,
 4321, 234, 31.8),

('coin-change', 'Coin Change', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'You are given an integer array coins representing coins of different denominations and an integer amount.',
 'def coinChange(self, coins: List[int], amount: int) -> int:',
 '[{"input": "coins = [1,3,4], amount = 6", "output": "2"}]'::jsonb,
 '["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"]'::jsonb,
 '["Use DP: minimum coins for each amount", "Build up from smaller amounts"]'::jsonb,
 6789, 234, 40.7),

('maximum-product-subarray', 'Maximum Product Subarray', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'Given an integer array nums, find a contiguous non-empty subarray within the array that has the largest product.',
 'def maxProduct(self, nums: List[int]) -> int:',
 '[{"input": "nums = [2,3,-2,4]", "output": "6"}, {"input": "nums = [-2,0,-1]", "output": "0"}]'::jsonb,
 '["1 <= nums.length <= 2 * 10^4", "-10 <= nums[i] <= 10"]'::jsonb,
 '["Track both max and min products", "Negative numbers can flip max/min"]'::jsonb,
 7890, 167, 34.9),

('word-break', 'Word Break', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'Given a string s and a dictionary of strings wordDict, return true if s can be segmented.',
 'def wordBreak(self, s: str, wordDict: List[str]) -> bool:',
 '[{"input": "s = \"leetcode\", wordDict = [\"leet\",\"code\"]", "output": "true"}]'::jsonb,
 '["1 <= s.length <= 300", "1 <= wordDict.length <= 1000"]'::jsonb,
 '["Use DP: can we break s[0:i]", "Check all possible word endings"]'::jsonb,
 5432, 189, 45.6),

('longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium',
 (SELECT id FROM categories WHERE name = '1-D Dynamic Programming'),
 'Given an integer array nums, return the length of the longest strictly increasing subsequence.',
 'def lengthOfLIS(self, nums: List[int]) -> int:',
 '[{"input": "nums = [10,9,2,5,3,7,101,18]", "output": "4"}]'::jsonb,
 '["1 <= nums.length <= 2500", "-10^4 <= nums[i] <= 10^4"]'::jsonb,
 '["DP: length of LIS ending at each position", "Binary search for O(n log n)"]'::jsonb,
 8765, 234, 54.3),

-- 2-D Dynamic Programming (2 problems)
('unique-paths', 'Unique Paths', 'Medium',
 (SELECT id FROM categories WHERE name = '2-D Dynamic Programming'),
 'There is a robot on an m x n grid. The robot can only move either down or right at any point in time.',
 'def uniquePaths(self, m: int, n: int) -> int:',
 '[{"input": "m = 3, n = 7", "output": "28"}, {"input": "m = 3, n = 2", "output": "3"}]'::jsonb,
 '["1 <= m, n <= 100"]'::jsonb,
 '["DP: paths[i][j] = paths[i-1][j] + paths[i][j-1]", "Can optimize space"]'::jsonb,
 6789, 123, 62.1),

('longest-common-subsequence', 'Longest Common Subsequence', 'Medium',
 (SELECT id FROM categories WHERE name = '2-D Dynamic Programming'),
 'Given two strings text1 and text2, return the length of their longest common subsequence.',
 'def longestCommonSubsequence(self, text1: str, text2: str) -> int:',
 '[{"input": "text1 = \"abcde\", text2 = \"ace\"", "output": "3"}]'::jsonb,
 '["1 <= text1.length, text2.length <= 1000", "text1 and text2 consist of only lowercase English characters"]'::jsonb,
 '["2D DP: compare characters", "If match: 1 + dp[i-1][j-1], else: max(dp[i-1][j], dp[i][j-1])"]'::jsonb,
 5678, 167, 58.7),

-- Greedy (2 problems)
('maximum-subarray', 'Maximum Subarray', 'Medium',
 (SELECT id FROM categories WHERE name = 'Greedy'),
 'Given an integer array nums, find the contiguous subarray which has the largest sum and return its sum.',
 'def maxSubArray(self, nums: List[int]) -> int:',
 '[{"input": "nums = [-2,1,-3,4,-1,2,1,-5,4]", "output": "6"}]'::jsonb,
 '["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"]'::jsonb,
 '["Kadanes algorithm", "Reset sum when it becomes negative"]'::jsonb,
 9876, 234, 50.1),

('jump-game', 'Jump Game', 'Medium',
 (SELECT id FROM categories WHERE name = 'Greedy'),
 'You are given an integer array nums. You are initially positioned at the arrays first index.',
 'def canJump(self, nums: List[int]) -> bool:',
 '[{"input": "nums = [2,3,1,1,4]", "output": "true"}, {"input": "nums = [3,2,1,0,4]", "output": "false"}]'::jsonb,
 '["1 <= nums.length <= 10^4", "0 <= nums[i] <= 10^5"]'::jsonb,
 '["Track furthest reachable position", "Greedy: always try to reach furthest"]'::jsonb,
 7890, 189, 38.4),

-- Intervals (5 problems)
('insert-interval', 'Insert Interval', 'Medium',
 (SELECT id FROM categories WHERE name = 'Intervals'),
 'You are given an array of non-overlapping intervals where intervals[i] = [starti, endi].',
 'def insert(self, intervals: List[List[int]], newInterval: List[int]) -> List[List[int]]:',
 '[{"input": "intervals = [[1,3],[6,9]], newInterval = [2,5]", "output": "[[1,5],[6,9]]"}]'::jsonb,
 '["0 <= intervals.length <= 10^4", "intervals[i].length == 2"]'::jsonb,
 '["Find position to insert", "Merge overlapping intervals"]'::jsonb,
 4567, 123, 38.9),

('merge-intervals', 'Merge Intervals', 'Medium',
 (SELECT id FROM categories WHERE name = 'Intervals'),
 'Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals.',
 'def merge(self, intervals: List[List[int]]) -> List[List[int]]:',
 '[{"input": "intervals = [[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]"}]'::jsonb,
 '["1 <= intervals.length <= 10^4", "intervals[i].length == 2"]'::jsonb,
 '["Sort by start time", "Merge overlapping intervals"]'::jsonb,
 6789, 234, 46.8),

('non-overlapping-intervals', 'Non-overlapping Intervals', 'Medium',
 (SELECT id FROM categories WHERE name = 'Intervals'),
 'Given an array of intervals, return the minimum number of intervals you need to remove.',
 'def eraseOverlapIntervals(self, intervals: List[List[int]]) -> int:',
 '[{"input": "intervals = [[1,2],[2,3],[3,4],[1,3]]", "output": "1"}]'::jsonb,
 '["1 <= intervals.length <= 10^5", "intervals[i].length == 2"]'::jsonb,
 '["Sort by end time", "Greedy: keep intervals with earliest end"]'::jsonb,
 3456, 167, 50.2),

('meeting-rooms', 'Meeting Rooms', 'Easy',
 (SELECT id FROM categories WHERE name = 'Intervals'),
 'Given an array of meeting time intervals, determine if a person could attend all meetings.',
 'def canAttendMeetings(self, intervals: List[List[int]]) -> bool:',
 '[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "false"}]'::jsonb,
 '["0 <= intervals.length <= 10^4", "intervals[i].length == 2"]'::jsonb,
 '["Sort by start time", "Check for overlaps"]'::jsonb,
 2345, 89, 56.7),

('meeting-rooms-ii', 'Meeting Rooms II', 'Medium',
 (SELECT id FROM categories WHERE name = 'Intervals'),
 'Given an array of meeting time intervals, return the minimum number of conference rooms required.',
 'def minMeetingRooms(self, intervals: List[List[int]]) -> int:',
 '[{"input": "intervals = [[0,30],[5,10],[15,20]]", "output": "2"}]'::jsonb,
 '["1 <= intervals.length <= 10^4", "intervals[i].length == 2"]'::jsonb,
 '["Use min heap for end times", "Track concurrent meetings"]'::jsonb,
 4567, 234, 49.1)

ON CONFLICT (id) DO NOTHING;